manifests/ca.pp
1. There was a typo in "distrust" that would have prevented string matching.
2. This change switched from a string comparison ($ca_text == undef) to using stdlib's "is_string" validator. Without this change certain keys could create invalid byte sequence
errors due to the string comparison:
> puppet Error: Could not retrieve catalog from remote server: Error
400 on SERVER: invalid byte sequence in US-ASCII
=> Validation errors

manifests/init.pp
Hi there!
Ran into a common issue with installing packages in Puppet for duplicate resources when using the puppet/nodejs module:
https://github.com/voxpupuli/puppet-nodejs/blob/master/manifests/repo/nodesource/apt.pp#L9
```
Feb 22 14:17:18 exampleserver puppet-agent[18599]: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Package[ca-certificates] is already declared; cannot redeclare at /etc/puppetlabs/code/environments/staging/modules/ca_cert/manifests/init.pp:70 at /etc/puppetlabs/code/environments/staging/modules/ca_cert/manifests/init.pp:70:5 on node exampleserver.example.com
```
For now we've opted to set `install_package: false` with this module but it makes our setup more …
=> Use stdlib ensure_packages for installing ca-certificates package

README.md, manifests/params.pp, metadata.json
The mechanism for ca updates works on opensuse 13 and 42 as well. (tested). Maybe in 42.2 something will change, but thats unlikely and even when...we can still update the manifest then.
=> Add Support for OpenSuSE 13 and 42 Leap

manifests/ca.pp, spec/defines/ca_spec.rb
our ca url happens to have a (1) in it now that it's been renewed once...the wget didn't handle that without the single quotes
=> handle paths/urls with special characters

manifests/ca.pp
This does nothing on the file. This just allows Puppet to be aware of the
existence of this file and avoid purging it if `purge_unmanaged_CAs` is
st to `true`.
Closes #29
=> Do not purge managed CA's

manifests/ca.pp, manifests/init.pp, manifests/params.pp, spec/classes/ca_cert_spec.rb, spec/classes/update_spec.rb
Allow Setting Ca file mode per certificate. Tested with Debian 8.
(i'm only submitting the PR, original work done by tmaher)
=> Allow Setting Ca file mode

manifests/ca.pp, manifests/enable.pp, manifests/update.pp
Put enable_ca_trust into separate class ca_cert::enable and make
ca_cert::ca resource type dependent on ca_cert::enable. This is to
avoid situations where the certificate file was being dropped even
though enable_ca_trust failed. When the issue causing enable_ca_trust to
fail was corrected, update_ca_trust would not execute due to the
certificate file already being dropped and refreshonly being set on
update_ca_trust.
Fixes pcfens/puppet-ca_cert#054
=> Fix dependency issue with dropping certificate

spec/classes/ca_cert_spec.rb, spec/spec_helper.rb
test for #50, test actually fails with
```     Failure/Error: it { should compile }
dependency cycles found: (File[ca1.pem] => Ca_cert::Ca[ca1] => Class[Ca_cert] => Ca_cert::Ca[ca1] => File[ca1.pem])
```
before https://github.com/pcfens/puppet-ca_cert/commit/4495f405fb2a5e01fdd8015af792e69c443c661a
=> test ca_certs::ca factory from hiera data

manifests/enable.pp, manifests/update.pp, spec/classes/update_spec.rb
parameter was moved from ca_cert::update to ca_cert but tests were not
@pcfens that interface change should have been a major version number
Please only release if the tests are actually ok
=> fix tests for `force_enable` parameter

manifests/ca.pp
The purpose of this PR is to get rid of this warning:
```
Warning: This method is deprecated, please use match expressions with Stdlib::Compat::String instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["/etc/puppetlabs/code/e
nvironments/production/modules/ca_cert/manifests/ca.pp", 47]:
(at /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
```
=> Use Puppet String data type to check if the variable is a string

manifests/init.pp
Treat `ca_cert::package_ensure: 'latest'` the same as the module would `present` or `installed`
=> Allow package_ensure to be "latest"

manifests/ca.pp
Fixes #64
Removing a cert should update-ca-trust.
=> fix: deleted certs should update-ca-trust

manifests/init.pp
This allows for better compatibility with puppetlabs-stdlib version 8 and use of `ensure_packages('ca-certificates')` (such as the puppet-openssl does) due to https://github.com/puppetlabs/puppetlabs-stdlib/pull/1196. Otherwise you can get a duplicate resource declaration error due to the mismatch in the ensure value.
I think #66 should _also_ be merged.
=> init: set package_ensure default to 'installed'

manifests/init.pp
If the package ca-certificates has already been declared someplace else in the codebase that uses ca_cert then this patch will prevent ca_cert from causing a duplicate declaration error.
Of course, one could argue that the user of the ca_cert module should just pass $install_package as false, and you may be right in that. But I see no harm in applying this patch.
=> Fix duplicate package declaration issue

manifests/ca.pp, metadata.json
Instead, use the Vox Pupuli archive module for fetching files over ftp, https, and http, since the lwf/remote_file module appears to be unmaintained (its last commit was in 2018).
=> replace lwf/remote_file with puppet/archive

manifests/params.pp
We have some Solaris 11 hosts where this module is handy. 
Documentation from Oracle: https://docs.oracle.com/cd/E53394_01/html/E54783/kmf-cacerts.html 
Tested on:
`$ uname -a
SunOS hostname 5.11 11.4.33.94.0 sun4v sparc sun4v 
`
=> Add support for Solaris 11

metadata.json
Tested on RHEL8 (New deployment of the host), had no Problems.
Untested params, but I'm pretty sure that there won't be any problems:
- ca_cert
- always_update_certs (only used default, false)
- purge_unmanaged_CAs (only used default, false)
- install_package (only used default, installed)
- ca_cert::ca
- ca_text
- source
- ftp
- http(s)
- file
- text
- verify_https_cert
- checksum
=> Add RHEL8 to supported operating systems

.fixtures.yml, manifests/ca.pp, manifests/enable.pp, manifests/params.pp, spec/acceptance/ca_cert_ca_spec.rb, spec/classes/ca_cert_spec.rb, spec/classes/params_spec.rb, spec/classes/update_spec.rb, spec/defines/ca_spec.rb
https://www.puppet.com/docs/puppet/latest/core_facts.html#legacy-facts
=> Replace legacy facts

manifests/init.pp, metadata.json
This is a rebase of #76 . I also updated the metadata.json to address the new required version.
=> fix: switch to namespaced function stdlib::ensure_packages; require puppetlabs/stdlib 9

.fixtures.yml
We don't need to declare the symlink anymore, puppetlabs_spec_helper will create it for us automatically.
=> .fixtures.yml: Remove legacy symlink

metadata.json
Debian, AIX and Solaris are supported based on the code in params.pp
This is a rework of 08e52e0c04d94542a226511010e41bfbdc29bdee in #81
=> Add supported OSes

manifests/params.pp, spec/classes/ca_cert_spec.rb
As mentioned in https://github.com/voxpupuli/puppet-ca_cert/pull/81#discussion_r1595753502 the debian defaults don't align with distro packages.
This PR corrects this and also align ca_file_mode across all distros.
=> Cleanup Debian defaults

README.md, manifests/ca.pp, manifests/params.pp, spec/classes/params_spec.rb, spec/defines/ca_spec.rb
Suse 10 an 11 support was dropped in #97
=> Remove code for EoL suse versions

spec/defines/ca_spec.rb
The code here is mostly pulled from #81 and adopted to the current state of master.
=> Refactor ca_cert:ca unit tests to use on_supported_os

REFERENCE.md, data/Archlinux-family.yaml, data/Debian-family.yaml, data/RedHat-family-9.yaml, manifests/ca.pp, manifests/init.pp, spec/acceptance/ca_cert_ca_spec.rb, spec/classes/ca_cert_spec.rb, spec/defines/ca_spec.rb
Rework of ca_cert::ca to support trusting and distrusting ca's provided by the ca-certificates package on Debian.
Also makes it possible to move from distrusted to trusted again on other distros ( ensure absent from `distrusted_cert_dir`)
To support this I have redefined the meaning of ca_cert::ca::ensure a bit
- present/absent is now used to manage certificates in `trusted_cert_dir`
- trusted/distrusted is now used to manage certificates in `distrusted_cert_dir` og Debian's `ca_certificates_conf`
`ca_cert::ca::ca_text`is renamed to `ca_cert::ca::content`and used directly as `file::content`
`ca_cert::ca::source` is now used directly as `archive::source`
`ca_cert::ca::verify_https_cert` parameter is renamed to `ca_cert::ca::allow_insecure_source` to better align with …
=> Support distrusting ca's on Debian; Changed ca_cert::ca parameter names and meaning

REFERENCE.md, manifests/ca.pp
Adding params to ca_cer::ca so that remote certificates can be downloaded truogh a proxy
Fixes #46
=> Support proxy when downloading remote certificates

.fixtures.yml, .sync.yml, spec/classes/ca_cert_spec.rb, spec/defines/ca_spec.rb, spec/spec_helper.rb
=> cleanup spec tests & facterdb_string_keys: switch to strings
